export enum Error {
  USER_NOT_FOUND = 'User not found',
  USER_ALREADY_EXISTS = 'User already exists',
  INVALID_CREDENTIALS = 'Invalid credentials',
  USER_MODIFICATION_FORBIDDEN = "You don't have permission to modify this user",
  COMPANY_MODIFICATION_FORBIDDEN = "You don't have permission to modify this company",
  COMPANY_NOT_FOUND = 'Company not found',
  COMPANY_ALREADY_EXISTS = 'Company already exists',
  COMPANY_ACCESS_FORBIDDEN = "You don't have permission to access this company",
  COMPANIES_NOT_FOUND = 'Companies not found',
  COMPANY_ID_REQUIRED = 'Company ID is required',
  ID_REQUIRED = 'ID is required',
  CUSTOMER_NOT_FOUND = 'Customer not found',
  CUSTOMERS_NOT_FOUND = 'Customers not found',
  CUSTOMER_MODIFICATION_FORBIDDEN = "You don't have permission to modify this customer",
  CUSTOMER_ALREADY_EXISTS = 'Customer already exists',
  CUSTOMER_ALREADY_EXISTS_FOR_COMPANY = 'This customer already exists for this company',
  DUPLICATE_EMAIL_OR_NAME = 'A customer with the same email or name already exists',
}
